### ISSUE TITLE
Doesn't read JSON file properly.

### ISSUE THREAD

**Issue by shiory602** [shiory602/CICCC-WMAD#1]
# Overview
I tried to read the JSON file which is created separately, then got an error when I run it.
```js
const http = require('http');
const fs = require('fs');

const server = http.createServer((req, res) => {
 fs.readFile('./json_response.json', 'UTF-8', (error, data) => {
    res.writeHead(200, { 'Content-Type': 'application/json'});
    res.writeHead(data);
    res.end( JSON.stringify(json_response) );
  })
})

server.listen(3000, console.log('server starts'));
```
# Assumed Procedure
1. Call `npm start`
2. I could get the detail of the JSON file in the browser.
# Problem
1. Call `npm start`
2. I have an error.

# Environment
- macOS
- High Sierra
- main branch latest version 
`c32f3ab1c19e7119bb43863db03e1152c5aee967`

# Errors, etc.
Data displayed in console.log is undefined
The console shows the following:
```
http_server.js:255
    throw new ERR_HTTP_INVALID_STATUS_CODE(originalStatusCode);
    ^

RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: {
  "status": 200, 
  "message": "successful" , 
  "result": [ "sunday" , "monday" , "tuesday" , "wednesday" ] , 
  "code": 2000
}
    at ServerResponse.writeHead (_http_server.js:255:11)
    at /Users/ShioriSuzuki/programing/ciccc-wmad/WMADーIvan/20210809/JSONsite/serve-json.js:18:9
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}
```

**Comment by shiory602** [comment]
# Functions for head and body
I wrote the code for the body with `writeHead`.
Then I edit `res.writeHead(data);` to `res.write(data);`

# Stringify
I had an error again:
```
/Users/ShioriSuzuki/programing/ciccc-wmad/WMADーIvan/20210809/JSONsite/serve-json.js:19
    res.end( JSON.stringify(json_response) );
                            ^

ReferenceError: json_response is not defined
    at /Users/ShioriSuzuki/programing/ciccc-wmad/WMADーIvan/20210809/JSONsite/serve-json.js:19:29
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```
So this time I remove `JSON.stringify(json_response)`, then it works.
## JSON.stringify()
`JSON.stringify` convert objects into json.
This time we don't need it, but why?

**Comment by shiory602** [comment]
# 'text/json' and 'application/json'
I could run both 'text/json' and 'application/json' .
```
res.writeHead(200, { 'Content-Type': 'text/json'});
```
Officially, they use `application/json`. [Ref](https://www.it-swarm-ja.com/ja/http/contenttype%EF%BC%9Atext-json%E3%81%A8application-json%E3%81%AE%E6%AD%A3%E7%A2%BA%E3%81%AA%E9%81%95%E3%81%84%E3%81%AF%E4%BD%95%E3%81%A7%E3%81%99%E3%81%8B%EF%BC%9F/1045014193/)
